# Generated by Django 4.2.3 on 2023-07-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=120)),
                ('jobTitle', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('softwareUserName', models.CharField(max_length=100)),
                ('expirationDate', models.DateTimeField()),
                ('version', models.CharField(max_length=50)),
            ],
        ),
    ]
